### ISSUE TITLE
wrong release path

### ISSUE THREAD

**Issue by eshubin** [arjan/pkgx#2]
Looks like by default relx puts release `into _rel/<name>/` rather than into `_rel`, as it's assumed by pkgx.

**Comment by arjan** [comment]
Thanks. This project hasn't been under my attention; relx has been changed since then, I'll try to update it soon (taking into account all the forks ;)

**Comment by eshubin** [comment]
Here is a fix https://github.com/RJ/pkgx/commit/9f8a294af97cbe152a2eacdd8a4971340e61ae22

**Comment by arjan** [comment]
Fixed by upgrading to rebar3
